"""complete profile session file fields

Revision ID: 6d5af1d90657
Revises: 6ddfa1da23f0
Create Date: 2026-06-09 20:27:09.904934
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6d5af1d90657'
down_revision: Union[str, Sequence[str], None] = '6ddfa1da23f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'files',
        sa.Column('purpose', sa.String(length=24), nullable=False, server_default='attachment'),
    )
    op.add_column('files', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('notes', sa.Text(), nullable=False, server_default=''))
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('mode', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'mode')
    op.drop_column('sessions', 'ended_at')
    op.drop_column('profiles', 'notes')
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'purpose')
    # ### end Alembic commands ###
