"""create core data tables

Revision ID: 6ddfa1da23f0
Revises: 
Create Date: 2026-06-09 19:55:08.396267
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ddfa1da23f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('can_long_term_preserve', sa.Boolean(), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('crisis_level', sa.String(length=24), nullable=True),
    sa.Column('initial_session_count', sa.Integer(), nullable=False),
    sa.Column('next_session_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_type'), 'profiles', ['type'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('replace_group_key', sa.String(length=120), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('analysis_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_category'), 'attachments', ['category'], unique=False)
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_attachments_user_id'), 'attachments', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.String(length=32), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('record_status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'sequence_no', name='sessions_profile_sequence_unique')
    )
    op.create_index(op.f('ix_sessions_occurred_at'), 'sessions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_sessions_profile_id'), 'sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_profile_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_occurred_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_attachments_user_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_category'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('users')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_type'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
