"""add authentication and profile access security

Revision ID: b9bd1730bf1b
Revises: 6d5af1d90657
Create Date: 2026-06-09 22:17:36.921342
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9bd1730bf1b'
down_revision: Union[str, Sequence[str], None] = '6d5af1d90657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_access_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_type', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_profile_access_grants_expires_at'), 'profile_access_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_profile_access_grants_profile_type'), 'profile_access_grants', ['profile_type'], unique=False)
    op.create_index(op.f('ix_profile_access_grants_user_id'), 'profile_access_grants', ['user_id'], unique=False)
    op.create_table('profile_access_passwords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_type', sa.String(length=24), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_type', name='profile_access_password_user_type_unique')
    )
    op.create_index(op.f('ix_profile_access_passwords_user_id'), 'profile_access_passwords', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_profile_access_passwords_user_id'), table_name='profile_access_passwords')
    op.drop_table('profile_access_passwords')
    op.drop_index(op.f('ix_profile_access_grants_user_id'), table_name='profile_access_grants')
    op.drop_index(op.f('ix_profile_access_grants_profile_type'), table_name='profile_access_grants')
    op.drop_index(op.f('ix_profile_access_grants_expires_at'), table_name='profile_access_grants')
    op.drop_table('profile_access_grants')
    # ### end Alembic commands ###
