"""add mvp workflow domains

Revision ID: e17d3cc5188b
Revises: b9bd1730bf1b
Create Date: 2026-06-09 22:26:03.593834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e17d3cc5188b'
down_revision: Union[str, Sequence[str], None] = 'b9bd1730bf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_job_type'), 'ai_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_ai_jobs_status'), 'ai_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_jobs_target_id'), 'ai_jobs', ['target_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_user_id'), 'ai_jobs', ['user_id'], unique=False)
    op.create_table('calendar_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('system_calendar_enabled', sa.Boolean(), nullable=False),
    sa.Column('privacy_title_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='calendar_settings_user_unique')
    )
    op.create_index(op.f('ix_calendar_settings_user_id'), 'calendar_settings', ['user_id'], unique=False)
    op.create_table('sensitive_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('owner_type', sa.String(length=48), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('origin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('can_long_term_preserve', sa.Boolean(), nullable=False),
    sa.Column('long_term_authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('long_term_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', name='sensitive_resources_resource_unique')
    )
    op.create_index(op.f('ix_sensitive_resources_expires_at'), 'sensitive_resources', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sensitive_resources_resource_id'), 'sensitive_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_sensitive_resources_resource_type'), 'sensitive_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_sensitive_resources_user_id'), 'sensitive_resources', ['user_id'], unique=False)
    op.create_table('supervision_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_conversations_expires_at'), 'supervision_conversations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_supervision_conversations_user_id'), 'supervision_conversations', ['user_id'], unique=False)
    op.create_table('supervision_context_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['supervision_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'resource_type', 'resource_id', name='supervision_context_unique')
    )
    op.create_index(op.f('ix_supervision_context_refs_conversation_id'), 'supervision_context_refs', ['conversation_id'], unique=False)
    op.create_table('supervision_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generation_status', sa.String(length=24), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['supervision_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervision_messages_conversation_id'), 'supervision_messages', ['conversation_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('privacy_title', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sync_to_system_calendar', sa.Boolean(), nullable=False),
    sa.Column('system_calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_start_at'), 'calendar_events', ['start_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('audio_file_id', sa.String(length=36), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('archive_status', sa.String(length=24), nullable=False),
    sa.Column('ai_status', sa.String(length=24), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='recordings_session_unique')
    )
    op.create_index(op.f('ix_recordings_user_id'), 'recordings', ['user_id'], unique=False)
    op.create_table('recording_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('main_summary', sa.Text(), nullable=False),
    sa.Column('chapter_overview', sa.JSON(), nullable=False),
    sa.Column('manual_edited', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', name='recording_summaries_recording_unique')
    )
    op.create_index(op.f('ix_recording_summaries_expires_at'), 'recording_summaries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_recording_summaries_recording_id'), 'recording_summaries', ['recording_id'], unique=False)
    op.create_index(op.f('ix_recording_summaries_user_id'), 'recording_summaries', ['user_id'], unique=False)
    op.create_table('recording_transcripts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('speakers_json', sa.JSON(), nullable=False),
    sa.Column('segments_json', sa.JSON(), nullable=False),
    sa.Column('manual_edited', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id', name='recording_transcripts_recording_unique')
    )
    op.create_index(op.f('ix_recording_transcripts_expires_at'), 'recording_transcripts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_recording_transcripts_recording_id'), 'recording_transcripts', ['recording_id'], unique=False)
    op.create_index(op.f('ix_recording_transcripts_user_id'), 'recording_transcripts', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('recording_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('draft_content', sa.JSON(), nullable=False),
    sa.Column('formal_content', sa.JSON(), nullable=True),
    sa.Column('selected_sources', sa.JSON(), nullable=False),
    sa.Column('generation_status', sa.String(length=24), nullable=False),
    sa.Column('formal_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_expires_at'), 'reports', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reports_profile_id'), 'reports', ['profile_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_session_id'), 'reports', ['session_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.add_column('attachments', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('files', sa.Column('checksum_sha256', sa.String(length=64), nullable=True))
    op.add_column('files', sa.Column('long_term_authorized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('files', sa.Column('long_term_revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'long_term_revoked_at')
    op.drop_column('files', 'long_term_authorized_at')
    op.drop_column('files', 'checksum_sha256')
    op.drop_column('attachments', 'extracted_text')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_session_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_profile_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_expires_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_recording_transcripts_user_id'), table_name='recording_transcripts')
    op.drop_index(op.f('ix_recording_transcripts_recording_id'), table_name='recording_transcripts')
    op.drop_index(op.f('ix_recording_transcripts_expires_at'), table_name='recording_transcripts')
    op.drop_table('recording_transcripts')
    op.drop_index(op.f('ix_recording_summaries_user_id'), table_name='recording_summaries')
    op.drop_index(op.f('ix_recording_summaries_recording_id'), table_name='recording_summaries')
    op.drop_index(op.f('ix_recording_summaries_expires_at'), table_name='recording_summaries')
    op.drop_table('recording_summaries')
    op.drop_index(op.f('ix_recordings_user_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_at'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_supervision_messages_conversation_id'), table_name='supervision_messages')
    op.drop_table('supervision_messages')
    op.drop_index(op.f('ix_supervision_context_refs_conversation_id'), table_name='supervision_context_refs')
    op.drop_table('supervision_context_refs')
    op.drop_index(op.f('ix_supervision_conversations_user_id'), table_name='supervision_conversations')
    op.drop_index(op.f('ix_supervision_conversations_expires_at'), table_name='supervision_conversations')
    op.drop_table('supervision_conversations')
    op.drop_index(op.f('ix_sensitive_resources_user_id'), table_name='sensitive_resources')
    op.drop_index(op.f('ix_sensitive_resources_resource_type'), table_name='sensitive_resources')
    op.drop_index(op.f('ix_sensitive_resources_resource_id'), table_name='sensitive_resources')
    op.drop_index(op.f('ix_sensitive_resources_expires_at'), table_name='sensitive_resources')
    op.drop_table('sensitive_resources')
    op.drop_index(op.f('ix_calendar_settings_user_id'), table_name='calendar_settings')
    op.drop_table('calendar_settings')
    op.drop_index(op.f('ix_ai_jobs_user_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_target_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_status'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_job_type'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
